# Numpy Giriş

##İçerik:
#1.

## 1.Numpy Array Oluşturma ve Temel Fonksiyonları

### Neden Numpy Arrayler daha hızlıdır?

NumPy dizileri, C dilinde optimize edilmiş altta yatan kütüphaneler tarafından desteklendiği için daha hızlıdır. 
Bu kütüphaneler, veri belleği üzerinde daha etkin bir şekilde yönetim sağlar ve doğrudan belleğe erişim sağlarlar, 
böylece veri işleme operasyonlarının daha hızlı gerçekleşmesini sağlarlar. Ayrıca, NumPynin vektörleştirilmiş 
operasyonları, Pythondaki döngülerden kaçınarak verimliliği artırır ve işlemleri paralel olarak gerçekleştirebilir,
bu da genellikle daha yüksek performansla sonuçlanır. 

### Veri Tahsisi Numpy:
    
Data Buffer: NumPydeki veri tamponu, dizinin boyutundan bağımsız olarak, gerçek elemanları depolayan tek bir, düz
    bloktur. Bu, etkin öğe bazlı işlemler ve veri erişimini mümkün kılar.

Shape: Bir dizinin şekli, her eksen boyunca boyutları temsil eden tam sayıların bir demetidir. Her tam sayı, 
    belirli bir boyutta dizinin boyutunu temsil eder. Bu boyutlar, diziyi doğru bir şekilde indekslemek ve yeniden 
    şekillendirmek için gereklidir.

Strides: Adımlar, bir sonraki öğeye geçerken her boyutta kaç bayt adım atılacağını belirleyen tam sayıların 
    demetleridir. Adımlar, bellekteki öğeler arasındaki boşluğu belirler ve her boyutta bir öğeden diğerine geçmek
    için kaç baytın gerektiğini ölçer.


In [1]:
# Burada bir numpy array oluşturmayı ve bu array'ın temel fonksiyonlarını göreceğiz

import numpy as np #Kütüphanemizi import ettik

#Bir listeyi numpy dizisi haline getirelim:

liste = [1, 2, 3, 4] 
numpyListArr = np.array(liste) #array() fonksiyonu ile dizi haline getirebiliriz

print("Liste =", liste, "listenin tipi =", type(liste)) 
print("Numpy array =", numpyListArr, "Numpyın tipi =", type(numpyListArr))

Liste = [1, 2, 3, 4] listenin tipi = <class 'list'>
Numpy array = [1 2 3 4] Numpyın tipi = <class 'numpy.ndarray'>


In [2]:
#Birden fazla listeyi numpy array'i haline getirmek

list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
 

more_array = np.array([list_1,
                       list_2,
                       list_3])
 
print("Numpy array =", more_array, "Numpyın tipi =", type(more_array))

Numpy array = [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] Numpyın tipi = <class 'numpy.ndarray'>


In [3]:
#Bir kelimeyi harflerine ayırarak numpy array'e atalım

var = "Halekmc"
 
kelime_array = np.fromiter(var, dtype = 'U2')
 
print("Numpy array =", kelime_array, "Numpyın tipi =", type(kelime_array))

Numpy array = ['H' 'a' 'l' 'e' 'k' 'm' 'c'] Numpyın tipi = <class 'numpy.ndarray'>


In [4]:
# Liste olmadan direk numpy aray oluşturalım

numpy_array = np.array( [[ 1, 2, 3], 
                        [ 4, 2, 5]] ) 

# Array'ın tipi type()
print(type(numpy_array)) 

# Kosegen sayısı  .ndim
print(numpy_array.ndim) 

# Array'ın boyutları 2x3 gibi .shape
print(numpy_array.shape) 

# Toplam Eleman Sayısı .size
print(numpy_array.size) 

# Elementlerin tipi int, float vb. / .dtype
print(numpy_array.dtype) 

<class 'numpy.ndarray'>
2
(2, 3)
6
int64


In [5]:
#3x4 boyutlarında içi boş bir array oluşturmak .empty
empty_array = np.empty((3, 4))
print(empty_array)


#3x4 boyutlarında içi 5 dolu bir array oluşturmak .full
full_array = np.full((3, 4), 5)
print(full_array)



[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.64233733e-067 5.33359692e-091 4.00769595e+174]
 [8.31525886e-072 4.04457680e-057 3.99910963e+252 1.46030983e-319]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [6]:
# Float cinsinden bir array oluşturma
float_array = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float') 
print ("Float Array:" , float_array) 
  
# Tuple Cinsinde bir array oluşturma
tuple_array = np.array((1 , 3, 2)) 
print ("\nTupple Array:", tuple_array)

Float Array: [[1. 2. 4.]
 [5. 8. 7.]]

Tupple Array: [1 3 2]


In [7]:
#Veri bilimi alanında sıklıkla başlangıçta bir dizi oluştururken veya bellek tahsisi yaparken kullanılır.

# İçi tamamen 0 olan 3x4 bir matris oluşturalım
zeros_array = np.zeros((3, 4)) 
print ("Zeros Array: \n", zeros_array) 

# İçi tamamen 1 olan 3x4 bir matris oluşturalım
ones_array = np.ones((3, 4)) 
print ("Ones Array: \n", ones_array) 

#Matematiksel hesaplamalarda kullanılır gerçek ve sanal kısımdan oluşur örn: 3+2j
# Komplex degerlerden olusan 3x3 bir matris olusturalim
full_array = np.full((3, 3), 6, dtype = 'complex') 
print ("Komplex Full Array\n", full_array) 

# 2x2 Random Degerlerden olusan bir matrix oluşturalım 
random_array = np.random.random((2, 2)) 
print ("Random Array:\n", random_array)


Zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Komplex Full Array
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
Random Array:
 [[0.96607319 0.4071488 ]
 [0.51095071 0.94033725]]


In [8]:
# 0 ile 40 arasında 5'er 5'er artan bir dizi, 40 dahil edilmez. Edilmesi istenirse +1 fazlası yazılır

f = np.arange(0, 40, 5) 
print ("40 dahil olmayan dizi:\n", f)

g = np.arange(0, 41, 5) 
print ("40 dahil olan dizi:\n", g)


40 dahil olmayan dizi:
 [ 0  5 10 15 20 25 30 35]
40 dahil olan dizi:
 [ 0  5 10 15 20 25 30 35 40]


In [9]:
# Belirli bir aralığı eşit aralıklar ile döndürür. Örn: 5 sayısını 10 eşit parcaya bolup dizi olusturmak gibi, 
# artış miktarları sabittir. Float cinsinden sayı gelebilir

linspace_array = np.linspace(0, 5, 10) 
print (linspace_array)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [10]:
# 3x4 boyutlarındaki bir matrisi 2x2x3 boyutlarına döndürme. Bunun icin reshape fonksiyonu kullanılır. Burada onemli
# olan notka donusturulen array'ın boyutlarının tutması. Örn:3x4 = 12, 2x2x3 = 12 gibi

original_array = np.array([[1, 2, 3, 4], 
                [5, 2, 4, 2], 
                [1, 2, 0, 1]]) 

reshape_array = original_array.reshape(2, 2, 3) 

print ("Orijinal:\n", original_array) 

print ("Donusturulmus:\n", reshape_array)


Orijinal:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Donusturulmus:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [11]:
#swapaxes fonksiyonu, belirtilen iki eksen arasında yer alan değerleri değiştirir. 

#Örneğin, swapaxes(arr, 0, 2) ifadesi, birinci eksenle üçüncü eksen arasındaki değerleri değiştirir.

original_array1 = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]]) 
  
swapaxes_array = np.swapaxes(original_array1, 0, 2) 
  
print (swapaxes_array) 

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [12]:
# Flatten array: Elimizde bulunan bir array'ı tek bir satır haline dönüştürmek. Örn: 2x3 olan matrisimiz flatten
# metodu ile 1x6 olacak

original_array2 = np.array([[1, 2, 3], [4, 5, 6]]) 
flat_array = original_array2.flatten() 

print ("Orijinal array:\n", original_array2) 
print ("Flatten array:\n", flat_array)


Orijinal array:
 [[1 2 3]
 [4 5 6]]
Flatten array:
 [1 2 3 4 5 6]


##Index in Arrays

In [13]:
#arr[:2, ::2] ifadesiyle ilk iki satır ve sütunların her ikincisi seçilir. ilk iki satırı ve sütunlarından 
#sıfırıncı ve ikinci sütunları alır.

original_array3 = np.array([[-1, 2, 0, 4], 
                [4, -0.5, 6, 0], 
                [2.6, 0, 7, 8], 
                [3, -7, 4, 2.0]]) 
  
# Slicing array 
slicing_array = original_array3[:2, ::2] 
print (slicing_array) 
  

[[-1.  0.]
 [ 4.  6.]]


In [14]:
#Numpy arrayler ile 4 işlem

original_array3 = np.array([1, 2, 5, 3]) 
  
# Her değere 1 eklemek 
print ("Her değere 1 eklemek:", original_array3+1) 
  
# Her değerden 3 çıkarmak
print ("Her değerden 3 çıkarmak:", original_array3-3)  
  
# Her değerin karesini alma:
print ("Her değerin karesini almak:", original_array3**2) 
  
# Her değerin iki katını almak
original_array3 *= 2
print ("Her değerin iki katını almak", original_array3) 
  


Her değere 1 eklemek: [2 3 6 4]
Her değerden 3 çıkarmak: [-2 -1  2  0]
Her değerin karesini almak: [ 1  4 25  9]
Her değerin iki katını almak [ 2  4 10  6]


In [15]:
# dizinin transpoz edilmesi
original_array4 = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]]) 
  
print ("\Orijinal array:\n", original_array4) 
print ("Transpoz array:\n", original_array4.T) 

\Orijinal array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpoz array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [16]:
#Numpy arraylar ile dizideki maks min ilişkileri

original_array5 = np.array([[1, 5, 6], 
                            [4, 7, 2], 
                            [3, 1, 9]]) 

# Dizideki en büyük elemanı bulmak
print ("En Büyük Eleman:", original_array5.max()) 

#Dizideki en büyük elemanları bulup dizi oluşturmak
print ("En Büyük Elemanlar:", original_array5.max(axis = 1)) 

# Dizideki en küçük elemanları bulup dizi oluşturmak
print ("En Küçük Elemanlar", original_array5.min(axis = 0)) 

# Dizideki rakamların toplamı
print ("Dizideki rakamların toplamı:", original_array5.sum()) 

# Her satırın kümülatif toplamı

#Örn: 1, 1+5=6, 1+5+6 = 12 gibi
print ("Her satırın kümülatif toplamı:\n", original_array5.cumsum(axis = 1)) 


En Büyük Eleman: 9
En Büyük Elemanlar: [6 7 9]
En Küçük Elemanlar [1 1 2]
Dizideki rakamların toplamı: 38
Her satırın kümülatif toplamı:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [17]:
#Arrayların Kendi içinde Toplanıp Çıkarılması


a = np.array([[1, 2], 
            [3, 4]]) 
b = np.array([[4, 3], 
            [2, 1]]) 

# Toplama
print ("Toplam:\n", a + b) 

# Çarpma
print ("Çarpım:\n", a*b) 

##Dot ile Çarpmanın farkı nedir?
#Çarpma da birimler kendi arasında çarpılır örneğin 1.matrisin 1.1 değeri ile 2.matrisin 1.1 değeri çarpılır. Dot
#ile çarpmada içe matrisler matris çarpımında çarpılır (formüle bakabilirsiniz)


# Matrislerin çarpımı
print ("Matrix çarpımı:\n", a.dot(b)) 


Toplam:
 [[5 5]
 [5 5]]
Çarpım:
 [[4 6]
 [6 4]]
Matrix çarpımı:
 [[ 8  5]
 [20 13]]


In [18]:
#Numpy ile matematiksel fonksiyonlar

# Dizideki her elemanın sinisunu hesaplar

sinus_array = np.linspace(0, 2*np.pi, 10)
# Bu noktalara karşılık gelen sinus değerlerini hesapla
print("Sinus Array:",np.sin(sinus_array)) 

# her bir elemanın üssünü e^x olarak hesaplar 
exp_array = np.array([0, 1, 2, 3]) 
print ("Exponent Array/", np.exp(exp_array)) 

# her bir elemanın karakök alır 
print ("Sqrt Array:", np.sqrt(exp_array)) 


Sinus Array: [ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]
Exponent Array/ [ 1.          2.71828183  7.3890561  20.08553692]
Sqrt Array: [0.         1.         1.41421356 1.73205081]


In [19]:
#Filtreleme fonksiyonları

filter_array= np.array([[1, 4, 2], 
                        [3, 4, 6], 
                        [0, -1, 5]]) 

# Elemanları küçükten büyüğe sıralar
print ("Sorted Array:\n", np.sort(filter_array, axis = None)) 

# Her satır kendi içinde (axis=1) sıralanır, axis degeri 0 olsaydı her sutun kendi icinde sıralanırdı
print ("Satır Sorted Array:\n", np.sort(filter_array, axis = 1)) 

# Her sütün kendi içinde (axis=1) sıralanır, axis degeri 0 olsaydı her sutun kendi icinde sıralanırdı
print ("Sütün Sorted Array:\n", np.sort(filter_array, axis = 0) )

# Spesifik bir parametreye göre sıralama yapılabilir. Üsttekiler ile aynı şekilde çalışır (axis değeri), tek fark
#burada yazdığımız kind parametresindeki sort ifadesinin algoritmik olmasıdır. Büyük veriler ile çalışırken anlamlı
#olur, göstermek için yazdım.

print ("Merge Sort\n", np.sort(filter_array, axis = 0, kind = 'mergesort')) 

Sorted Array:
 [-1  0  1  2  3  4  4  5  6]
Satır Sorted Array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Sütün Sorted Array:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]
Merge Sort
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [20]:
#İçinde birden fazla tipi olan arraylerin sıralanması.


# Veri tipleri için takma adları belirleme
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Dizide bulunacak değerler
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
          ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

# Yapılandırılmış bir dizi oluşturma
veritipleri_array = np.array(values, dtype=dtypes)

# İsimlere göre sıralanmış dizi
print("\nİsimlere göre sıralanmış dizi:\n",
      np.sort(veritipleri_array, order='name'))

# Mezuniyet yılına ve ardından not ortalamasına göre sıralanmış dizi
print("Mezuniyet yılına ve not ortalamasına göre sıralanmış dizi:\n",
      np.sort(veritipleri_array, order=['grad_year', 'cgpa']))



İsimlere göre sıralanmış dizi:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Mezuniyet yılına ve not ortalamasına göre sıralanmış dizi:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [21]:
filter_array2 = [1, 2, 2, 3, 3, 3, 4, 5, 6, 6] 
print("Array = {}".format(filter_array2)) 

# Sol taraftaki 3'ün indeksini bulma
print("sol taraftaki indeks = {}".format(np.searchsorted(filter_array2, 3, side="left"))) 

# Sağ taraftaki 3'ün en sağ indeksini bulma 
print("sağ taraftaki indeks = {}".format(np.searchsorted(filter_array2, 3, side="right")))


Array = [1, 2, 2, 3, 3, 3, 4, 5, 6, 6]
sol taraftaki indeks = 3
sağ taraftaki indeks = 6


In [22]:
filter_array3 = np.array([9, 3, 1, 7, 4, 3, 6])

print("arr = {}".format(filter_array3)) 
  
#  i aranan degerin nerede olduguna bakar 
i = np.where(filter_array3 == 1) 
print("i = {}".format(i))

arr = [9 3 1 7 4 3 6]
i = (array([2]),)


In [23]:
#Eye fonksiyonu, birim matris oluşturmak için kullanılır. Birim matris, köşegeni boyunca birler ve geri kalan 
#yerlerde sıfırlar içeren kare bir matristir.

# 3x3 boyutlarında birim matris oluşturma
identity_matrix = np.eye(3)
print("Birim matris:")
print(identity_matrix)


# 5x5 boyutlarında, köşegenin 1 birim sağında yer alanlar için 1'ler içeren özel bir matris oluşturma
custom_matrix = np.eye(5, k=1)
print("Özel matris:")
print(custom_matrix)



Birim matris:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Özel matris:
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


##Dizileri birleştirme

In [24]:
original_array6 = np.array([2, 4, 6, 8, 10])

# Dizinin bir kopyasını oluşturma
copy_array = original_array6.copy()

# Diziler farklı kimliklere sahiptir
print("Orijinal'in kimliği:", id(original_array6))
print("Copy'nin kimliği:", id(copy_array))

# Orijinal diziyi değiştirme
# Bu, kopyayı etkilemeyecektir
original_array6[0] = 12

# Diziyi ve kopyayı yazdırma
print("Orijinal dizi:", original_array6)
print("Kopya:", copy_array)

Orijinal'in kimliği: 140372430707888
Copy'nin kimliği: 140372430707984
Orijinal dizi: [12  4  6  8 10]
Kopya: [ 2  4  6  8 10]


In [25]:
#Diziye eleman ekleme

original_array7 = np.array([1, 8, 3, 3, 5])
print('Orijinal Dizi : ', original_array7)

# Diziye bir eleman eklemek için np.append() fonksiyonu kullanma
original_array7 = np.append(original_array7, [7])
print('Eleman eklendikten sonraki Dizi : ', original_array7)

Orijinal Dizi :  [1 8 3 3 5]
Eleman eklendikten sonraki Dizi :  [1 8 3 3 5 7]


In [26]:
#Array birleştirme append()


ekleme_array1 = np.array([1, 2, 3])
print('Birinci array: ', ekleme_array1)
 
ekleme_array2 = np.array([4, 5, 6])
print('İkinci array : ', ekleme_array2)

ekleme_array3 = np.array([4.0, 5.0])
print('Üçüncü float array : ', ekleme_array3)

 
# Arrayleri birleştirelim
birlesik_array = np.append(ekleme_array1, ekleme_array2)
print('Birleşik array : ', birlesik_array)


# Float cinsinden birlestirme
birlesik_array_float = np.append(ekleme_array1, ekleme_array2)

# Birleştirilmiş diziyi ekrana yazdırma
print(birlesik_array_float )


Birinci array:  [1 2 3]
İkinci array :  [4 5 6]
Üçüncü float array :  [4. 5.]
Birleşik array :  [1 2 3 4 5 6]
[1 2 3 4 5 6]


In [27]:
##Append ve concatenate farkı nedir?##

#np.concatenate() fonksiyonu, dizilerin boyutlarını genişletmek için kullanılırken, np.append() fonksiyonu tek bir 
#boyutlu dizileri genişletmek için kullanılır. np.concatenate() ile birden fazla boyutlu dizileri birleştirebilirsiniz,
#ancak np.append() fonksiyonu sadece tek boyutlu diziler üzerinde çalışır.

#!Daha büyük veri setleri için concatenate kullanımı daha efektiftir !


#Yukarıdaki ekleme arraylerini kullanalım

# diziler birleştirilir

# axis=0 parametresi, birleştirme işleminin satırlar boyunca yapılmasını sağlar
birlesik_array2 = np.concatenate((ekleme_array1, ekleme_array2), axis=0)

# Birleştirilmiş diziyi ekrana yazdırma
print(birlesik_array2)


[1 2 3 4 5 6]


In [28]:
# NumPy dizisindeki sütunları yer değiştirmek

orijinal_array8 = np.arange(12).reshape(4, 3)

print("Orijinal Array : ")
print(orijinal_array8)

# Yer değiştirmek için bir fonksiyon oluşturma
def Swap(arr, baslangic_indeksi, son_indeksi):
    arr[:, [baslangic_indeksi, son_indeksi]] = arr[:, [son_indeksi, baslangic_indeksi]]

# Fonksiyonu çağırma ve parametrelerle birlikte kullanma
Swap(orijinal_array8, 0, 1)

print(" Yer Değiştirdikten Sonra :")
print(orijinal_array8)


Orijinal Array : 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
 Yer Değiştirdikten Sonra :
[[ 1  0  2]
 [ 4  3  5]
 [ 7  6  8]
 [10  9 11]]


In [29]:
#Diziyi yatay olarak birleştirme
#Concatenate fonksiyonun axis degeri ile de aynı islem yapılabilir. Bilmeniz acısından ekledim.

orijinal_array9 = np.array([1, 2, 3])
print("1.Dizi:\n", orijinal_array9)

orijinal_array10 = np.array([4, 5, 6])
print("2.Dizi:\n", orijinal_array10)

# İki diziyi yatay olarak birleştirme
yatay_array = np.hstack((orijinal_array9, orijinal_array10))
print("Yatay olarak birleştirilmiş dizi:\n", yatay_array)


#VStack
  
dikey_array = np.vstack((orijinal_array9, orijinal_array10)) 
print ("Dikey olarak birleştirilmiş dizi:\n ", dikey_array) 


1.Dizi:
 [1 2 3]
2.Dizi:
 [4 5 6]
Yatay olarak birleştirilmiş dizi:
 [1 2 3 4 5 6]
Dikey olarak birleştirilmiş dizi:
  [[1 2 3]
 [4 5 6]]


In [30]:
##Stack ve concatenate farkı nedir ?#

#stack() dizileri yeni bir boyuta yerleştirirken, concatenate() fonksiyonu sadece belirtilen eksen boyunca birleştirir. 
#yeni bir boyut istenirse ->stack , #boyut aynı ise ->concatenate


# Dizileri yatay olarak birleştirme, 
stack_array = np.stack((orijinal_array9, orijinal_array10), axis=1) 
print(stack_array)


[[1 4]
 [2 5]
 [3 6]]


In [31]:
# block ile farklı boyutlardaki diziler birleştirilir


block_array1 = np.array([[1, 1], [1, 1]]) 
block_array2 = np.array([[2, 2, 2], [2, 2, 2]]) 
block_array3 = np.array([[3, 3], [3, 3], [3, 3]]) 
block_array4 = np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4]]) 

# np.block() fonksiyonunu kullanarak dizileri birleştirme
block_birlestirme = np.block([ 
    [block_array1, block_array2], 
    [block_array3, block_array4] 
]) 

# Birleştirilmiş diziyi ekrana yazdırma
print(block_birlestirme)


[[1 1 2 2 2]
 [1 1 2 2 2]
 [3 3 4 4 4]
 [3 3 4 4 4]
 [3 3 4 4 4]]


In [32]:
#dstack ile birlestirme
#dizileri derinlik boyutunda birleştirilir.

print("1.Dizi:\n", orijinal_array9)
print("2.Dizi:\n", orijinal_array10)


print("Birlestirilmis dizi:\n",np.dstack((orijinal_array9, orijinal_array10))) 

1.Dizi:
 [1 2 3]
2.Dizi:
 [4 5 6]
Birlestirilmis dizi:
 [[[1 4]
  [2 5]
  [3 6]]]


##Dizileri bölme / parçalama yöntemleri

In [33]:
orijinal_array11 = np.arange(6)
 
# arrayı x parcaya boler, x =2
split_array = np.split(orijinal_array11, 2)
 
print("Array:",orijinal_array11 )
print("\nSplit Array:",split_array)


Array: [0 1 2 3 4 5]

Split Array: [array([0, 1, 2]), array([3, 4, 5])]


In [34]:
orijinal_array12 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])
 
# axis=0 boyunca 2 alt diziye dikey bölme
vsplit_array = np.vsplit(orijinal_array12, 2)
 

print("V Split Array:", vsplit_array)


V Split Array: [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [35]:
# Orijinal bir 3D NumPy dizisi oluşturma
orijinal_array13 = np.arange(24).reshape((2, 3, 4))
 
# axis=2 boyunca (üçüncü eksende) 2 alt diziye bölmek
dsplit_array = np.dsplit(orijinal_array13, 2)
 

print("D Split Array:",dsplit_array)

D Split Array: [array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


In [36]:
#Union Array

#İki diziyi tekil şekilde birleştirir örn: 2 dizide de 20 varsa bunu bir kez yazar

orijinal_array14 = np.array([10, 20, 30, 40]) 

orijinal_array15 = np.array([20, 40, 60, 80]) 

  
# İki dizinin birleşimini hesaplama ve ekrana yazdırma
print("Union Array: :", np.union1d(orijinal_array14, orijinal_array15))

Union Array: : [10 20 30 40 60 80]


In [37]:
#UniqueRows : Benzersiz değerleri ayırır

orijinal_array16 = np.array([[11, 11, 12, 11],
                             [13, 11, 12, 11],
                             [16, 11, 12, 11],
                             [11, 11, 12, 11]])
 
 
uniqueRows = np.unique(orijinal_array16)
                        


print('Unique Rows:',uniqueRows, sep = '\n')

Unique Rows:
[11 12 13 16]


In [38]:
#Bir dizinin sonundaki gereksiz sıfırları silerek diziyi döndürür
#Örn:zaman serilerinde baştaki - sondaki sıfırlar genelde önemsiz oldugu icin silinerek veriye daha rahat odaklanılır

orijinal_array17 = np.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0)) 
  

# sonundaki gereksiz sıfırları içermeyen bir dizi döndürür
trim_array = np.trim_zeros(orijinal_array17, 'b') 
print(trim_array)

[ 0  0  0  0  1  5  7  0  6  2  9  0 10]


##Determinant Hesaplama

In [39]:
orijinal_array18 = np.array([[55, 25, 15], 
                    [30, 44, 2], 
                    [11, 45, 77]]) 



# Matrisin determinantını hesaplama
det_array = np.linalg.det(orijinal_array18) 

print("Matrix Determinantı:", det_array) 



Matrix Determinantı: 137180.0000000001
